### ISSUE TITLE
(Jason.DecodeError) unexpected end of input at position 0

### ISSUE THREAD

**Issue by Thaodan** [progval/matrix2051#24]
I noticed while testing the client with circe I get these random erros while lurking in #matrix@matrix.org:

```
00:30:54.864 [error] Task #PID<0.1237.0> started from #PID<0.1211.0> terminating
** (Jason.DecodeError) unexpected end of input at position 0
    (jason 1.3.0) lib/jason.ex:92: Jason.decode!/2
    (matrix2051 0.1.0) lib/matrix/raw_client.ex:45: M51.Matrix.RawClient.get/4
    (matrix2051 0.1.0) lib/matrix_client/poller.ex:83: M51.MatrixClient.Poller.poll_one/4
    (matrix2051 0.1.0) lib/matrix_client/poller.ex:59: M51.MatrixClient.Poller.loop_poll/3
    (elixir 1.13.2) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &M51.MatrixClient.Poller.poll/1
    Args: [{#PID<0.1211.0>}]
 ```

**Comment by progval** [comment]
Looks like the server sent an empty response for some reason; we'll need to log this properly instead of crashing.

**Comment by mk-fg** [comment]
`(matrix2051 0.1.0) lib/matrix/raw_client.ex:45: M51.Matrix.RawClient.get/4` seem to be an error-case, i.e. it some http error code with an empty body, not a normal 200 response.
```
      {:ok, %HTTPoison.Response{status_code: status_code, body: body}} ->
        {:error, status_code, Jason.decode!(body)}
```
