### ISSUE TITLE
receive timeout when connecting to matrix.org

### ISSUE THREAD

**Issue by terminaldweller** [progval/matrix2051#62]
i have started getting timeouts when i try to connect to `matrix.org`:

```
x2051-matrix2051_matrix-1  | 01:07:51.246 [info]  Incoming connection from ::ffff:172.24.0.1:56404
matrix2051-matrix2051_matrix-1  |
matrix2051-matrix2051_matrix-1  | 01:07:56.794 [error] GenServer {M51.Registry, {#PID, :matrix_client}} terminating
matrix2051-matrix2051_matrix-1  | ** (HTTPoison.Error) :timeout
matrix2051-matrix2051_matrix-1  |     (httpoison 1.8.2) lib/httpoison.ex:258: HTTPoison.request!/5
matrix2051-matrix2051_matrix-1  |     (matrix2051 0.1.0) lib/matrix_client/client.ex:114: M51.MatrixClient.Client.handle_call/3
matrix2051-matrix2051_matrix-1  |     (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
matrix2051-matrix2051_matrix-1  |     (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
matrix2051-matrix2051_matrix-1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
matrix2051-matrix2051_matrix-1  | Last message (from #PID): {:connect, "terminaldweller", "matrix.org", "mypassword"}
matrix2051-matrix2051_matrix-1  |
matrix2051-matrix2051_matrix-1  | 01:07:56.795 [error] Task #PID started from #PID terminating
matrix2051-matrix2051_matrix-1  | ** (stop) exited in: GenServer.call({:via, Registry, {M51.Registry, {#PID, :matrix_client}}}, {:connect, "terminaldweller", "matrix.org", "mypassword"}, 65000)
matrix2051-matrix2051_matrix-1  |     ** (EXIT) an exception was raised:
matrix2051-matrix2051_matrix-1  |         ** (HTTPoison.Error) :timeout
matrix2051-matrix2051_matrix-1  |             (httpoison 1.8.2) lib/httpoison.ex:258: HTTPoison.request!/5
matrix2051-matrix2051_matrix-1  |             (matrix2051 0.1.0) lib/matrix_client/client.ex:114: M51.MatrixClient.Client.handle_call/3
matrix2051-matrix2051_matrix-1  |             (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
matrix2051-matrix2051_matrix-1  |             (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
matrix2051-matrix2051_matrix-1  |             (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
matrix2051-matrix2051_matrix-1  |     (elixir 1.10.3) lib/gen_server.ex:1023: GenServer.call/3
matrix2051-matrix2051_matrix-1  |     (matrix2051 0.1.0) lib/irc/handler.ex:440: M51.IrcConn.Handler.handle_connreg/3
matrix2051-matrix2051_matrix-1  |     (matrix2051 0.1.0) lib/irc/handler.ex:171: M51.IrcConn.Handler.loop_connreg_iter/6
matrix2051-matrix2051_matrix-1  |     (matrix2051 0.1.0) lib/irc/handler.ex:149: M51.IrcConn.Handler.loop_connreg/5
matrix2051-matrix2051_matrix-1  |     (matrix2051 0.1.0) lib/irc/handler.ex:123: M51.IrcConn.Handler.run/1
matrix2051-matrix2051_matrix-1  |     (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
matrix2051-matrix2051_matrix-1  |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
matrix2051-matrix2051_matrix-1  | Function: &M51.IrcConn.Handler.run/1
```

I run my own matrix instance also. I haven''t updated synapse in a while. matrix2051 has no trouble connecting to that.

**Comment by progval** [comment]
Again? I already tripled the timeout because of matrix.org last august...

**Comment by terminaldweller** [comment]
it is happening again with matrix.org

**Comment by progval** [comment]
With #63 applied? What is the error exactly?

**Comment by progval** [comment]
Fixed by https://github.com/progval/matrix2051/commit/bb79c7d0570ffb7cb088c91cf0b1c7d8cd880c4b
